# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Proxy to use. In addition to the listed values, you can use a
# `socks://...` or `http://...` URL.
# Type: Proxy
# Valid values:
#   - system: Use the system wide proxy.
#   - none: Don't use any proxy
c.content.proxy = 'none'

# Validate SSL handshakes.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
c.content.ssl_strict = True

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = ['https://www.baidu.com/']

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = '#fabd2f'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#555555'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#a89984'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#504945'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#a89984'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#504945'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = 'black'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#a89984'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#282828'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#a89984'

# Bindings for normal mode
config.bind('<Ctrl+i>', 'open-editor')
config.bind('<Ctrl+o>', 'back')
config.bind('\\;', 'spawn --userscript ydcv')
config.bind('t', 'set-cmd-text -s :open -t')

# Bindings for command mode
config.bind('<Down>', 'command-history-next', mode='command')
config.bind('<Up>', 'command-history-prev', mode='command')

# Bindings for insert mode
config.bind('<Ctrl+k>', 'fake-key <Shift-End> ;; fake-key <Delete>', mode='insert')
config.bind('<Ctrl+u>', 'fake-key <Shift+Home> ;; fake-key <Delete>', mode='insert')
config.bind('<Ctrl+w>', 'fake-key <Ctrl-backspace>', mode='insert')
